### ISSUE TITLE
Make polling frequency configurable

### ISSUE THREAD

**Issue by DaveLinger** [LukeWinikates/homebridge-sleepme#76]
**Is your feature request related to a problem? Please describe:**
If the dock's status changes independently of the Apple Home app (via the sleepme app or due to scheduled progamming), the current state of the dock is often very delayed/wrong in the Apple Home app. This affects the state of the dock (on/off), target temp, and current temp.

**Describe the solution you'd like:**
I saw in the source that the polling thresholds are fixed values. I'd like to see those values optionally pulled in from the homebridge config. It looks like by default the "fast polling threshold" is 15 seconds and the "slow polling threshold" is 15 minutes?

**Describe alternatives you've considered:**
Well I guess I could fork and modify the code myself but I don't know a lot of javascript so I'd probably just be modifying the fixed values in the code.

**Additional context:**
I don't know in what cases which type of polling frequency is used. I don't know what rate limits sleepme puts on API usage.

**Comment by LukeWinikates** [comment]
Hi @DaveLinger - thanks for opening this issue. I think making these configurable is reasonable, and reducing the default polling times might be as well. I'll take a look at this and put it in the next release.

**Comment by LukeWinikates** [comment]
Version [0.2.0](../releases/tag/v0.2.0) switches to on-demand fetching of device status, so the staleness associated with polling should no longer be a problem.
